######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 15 16:12:09 2012
######################################################################

QT += declarative
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
